/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button.vue')['default']
    DateRangePicker: typeof import('./src/components/ui/date-range-picker.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    HomeItemV3: typeof import('./src/components/home-item-v3/home-item-v3.vue')['default']
    HomeItemV9: typeof import('./src/components/home-item-v9/home-item-v9.vue')['default']
    Icon: typeof import('./src/components/ui/icon.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    Navbar: typeof import('./src/components/ui/navbar.vue')['default']
    Rating: typeof import('./src/components/ui/rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    TabBarOriginal: typeof import('./src/components/tab-bar/tab-bar-original.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs.vue')['default']
  }
}
